---
title: "Exploratory Data Analysis: Correlation Analysis"
---

```{r}
# install packages
install.packages("corrplot")
install.packages("ggplot2")
```

```{r}
# import packages
library(ggplot2)
library(corrplot)
```

```{r}
df <- read.csv("Chapter04Dataset.csv")
```

```{r}
head(df)
```

```{r}
summary(df)
```
```{r}
cor(df)
write.csv(cor(df), "correlation.csv")  # export into a csv file
```
```{r}
corrplot(cor(df), method="number")
```

```{r}
# Correlations with significance levels
library(Hmisc)
rcorr(as.matrix(df), type="pearson") # type can be pearson or spearman
```
```{r}
panel.cor <- function(x, y, digits=2, cex.cor)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y))
  txt <- format(c(r, 0.123456789), digits=digits)[1]
  test <- cor.test(x,y)
  Signif <- ifelse(round(test$p.value,3)<0.001,"p<0.001",paste("p=",round(test$p.value,3)))  
  text(0.5, 0.25, paste("r=",txt))
  text(.5, .75, Signif)
}
panel.smooth<-function (x, y, col = "blue", bg = NA, pch = 18, 
                        cex = 0.8, col.smooth = "red", span = 2/3, iter = 3, ...) 
{
  points(x, y, pch = pch, col = col, bg = bg, cex = cex)
  ok <- is.finite(x) & is.finite(y)
  if (any(ok)) 
    lines(stats::lowess(x[ok], y[ok], f = span, iter = iter), 
          col = col.smooth, ...)
}
panel.hist <- function(x, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(usr[1:2], 0, 1.5) )
  h <- hist(x, plot = FALSE)
  breaks <- h$breaks; nB <- length(breaks)
  y <- h$counts; y <- y/max(y)
  rect(breaks[-nB], 0, breaks[-1], y, col="cyan", ...)
}
pairs(df, lower.panel=panel.smooth, upper.panel=panel.cor,diag.panel=panel.hist)
```

